[package]
name = "cryptid"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

[dependencies]
# hashbrown = { version = "0.1", features = ["nightly"] }
fxhash = "0.2"
stopwatch = "0.0"
